version: 1.0.{build}
configuration: Release
platform:
- x86
- x64
clone_folder: C:\projects\x64dbg-python
build:
  verbosity: normal
branches:
  only:
  - v25
# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - echo This is batch
  # batch commands start from cmd:
  - cmd: echo This is batch again
  - cmd: set MY_VAR=12345
  - cinst swig
# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:
  - cmd: call setenv.bat